import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Airplay,
  Anchor,
  Atom,
  Award,
  Axe,
  Beaker,
  Bike,
  Bot,
  Box,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  Code,
  Cpu,
  Factory,
  Flame,
  Gamepad2,
  Gauge,
  GitBranch,
  Globe,
  Hammer,
  HardHat,
  Heart,
  Hexagon,
  Key,
  Lightbulb,
  Magnet,
  Microscope,
  Mountain,
  Package,
  PenTool,
  Rocket,
  Ruler,
  Satellite,
  Shield,
  Sparkles,
  Star,
  Target,
  Telescope,
  Truck,
  Wrench,
  Zap,
} from 'lucide-react';

const RAW_PROJECT_ICONS = [
  { key: 'activity', label: 'Activity', Icon: Activity },
  { key: 'airplay', label: 'Airplay', Icon: Airplay },
  { key: 'anchor', label: 'Anchor', Icon: Anchor },
  { key: 'atom', label: 'Atom', Icon: Atom },
  { key: 'award', label: 'Award', Icon: Award },
  { key: 'axe', label: 'Axe', Icon: Axe },
  { key: 'beaker', label: 'Beaker', Icon: Beaker },
  { key: 'bike', label: 'Bike', Icon: Bike },
  { key: 'bot', label: 'Bot', Icon: Bot },
  { key: 'box', label: 'Box', Icon: Box },
  { key: 'briefcase', label: 'Briefcase', Icon: Briefcase },
  { key: 'building', label: 'Building', Icon: Building2 },
  { key: 'bus', label: 'Bus', Icon: Bus },
  { key: 'camera', label: 'Camera', Icon: Camera },
  { key: 'car', label: 'Car', Icon: Car },
  { key: 'code', label: 'Code', Icon: Code },
  { key: 'cpu', label: 'CPU', Icon: Cpu },
  { key: 'factory', label: 'Factory', Icon: Factory },
  { key: 'flame', label: 'Flame', Icon: Flame },
  { key: 'gamepad', label: 'Gamepad', Icon: Gamepad2 },
  { key: 'gauge', label: 'Gauge', Icon: Gauge },
  { key: 'git-branch', label: 'Git Branch', Icon: GitBranch },
  { key: 'globe', label: 'Globe', Icon: Globe },
  { key: 'hammer', label: 'Hammer', Icon: Hammer },
  { key: 'hard-hat', label: 'Hard Hat', Icon: HardHat },
  { key: 'heart', label: 'Heart', Icon: Heart },
  { key: 'hexagon', label: 'Hexagon', Icon: Hexagon },
  { key: 'key', label: 'Key', Icon: Key },
  { key: 'lightbulb', label: 'Lightbulb', Icon: Lightbulb },
  { key: 'magnet', label: 'Magnet', Icon: Magnet },
  { key: 'microscope', label: 'Microscope', Icon: Microscope },
  { key: 'mountain', label: 'Mountain', Icon: Mountain },
  { key: 'package', label: 'Package', Icon: Package },
  { key: 'pen-tool', label: 'Pen Tool', Icon: PenTool },
  { key: 'rocket', label: 'Rocket', Icon: Rocket },
  { key: 'ruler', label: 'Ruler', Icon: Ruler },
  { key: 'satellite', label: 'Satellite', Icon: Satellite },
  { key: 'shield', label: 'Shield', Icon: Shield },
  { key: 'sparkles', label: 'Sparkles', Icon: Sparkles },
  { key: 'star', label: 'Star', Icon: Star },
  { key: 'target', label: 'Target', Icon: Target },
  { key: 'telescope', label: 'Telescope', Icon: Telescope },
  { key: 'truck', label: 'Truck', Icon: Truck },
  { key: 'wrench', label: 'Wrench', Icon: Wrench },
  { key: 'zap', label: 'Zap', Icon: Zap },
];

export const PROJECT_ICONS = RAW_PROJECT_ICONS.filter((icon) => !!icon.Icon);

export const PROJECT_ICON_MAP = PROJECT_ICONS.reduce<Record<string, LucideIcon>>(
  (acc, icon) => {
    acc[icon.key] = icon.Icon;
    return acc;
  },
  {}
);
